### ISSUE TITLE
__webpack_modules__ is not defined

### ISSUE THREAD

**Issue by marcoroganovic** [borisirota/webworkify-webpack#31]
Hi there, I've researched for similar error but could not find answer so I decided to post it here.

Does anybody know what could be a problem? Because same setup worked until I merged something and that didn't actually modified place where this error happened.

```  
main: __webpack_modules__
          ^

ReferenceError: __webpack_modules__ is not defined
    at module.exports (/Users/vhmac/Developer/abago/node_modules/webworkify-webpack/index.js:154:11)
    at Object.<anonymous> (/Users/vhmac/Developer/abago/src/store/index.js:21:16)
    at Module._compile (module.js:571:32)
    at loader (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)```

**Comment by borisirota** [comment]
Hi @marcoroganovic, maybe you're trying to execute this module out of the `webpack` context ? This module works only within `webpack` bundle.

**Comment by borisirota** [comment]
I'm closing this issue since I didn't get any feedback and I'm not sure its an issue with the `webworkify-webpack` module.  
Feel free to reopen if it isn't fixed and you think its a bug with this module.
